### ISSUE TITLE
Definir niveles de complejidad de las aplicaciones promovidas en Firebase-Increible

### ISSUE THREAD

**Issue by jqEmprendedorVE** [firebaseve/firebase-increible#10]
## La meta es poder colocar una referencia a los Items de nuestra Lista de Aplicaciones

Para la definición de la complejidad podríamos medirla así:

- Cinta blanca [básico] :eyes: 
- Ninja [Intermedio] :running_man: 
- Jedi [Avanzado] :bowing_man: 
- Iluminado [Firebase Increible] :sunny: 

Igual es para abrir conversación y escuchar ideas

**Comment by Villanuevand** [comment]
Para mejorar la elección, seria bueno colocar un conjunto de opciones por comentario.

Ejemplo:

-  Básico (emoji)
- Intermedio (emoji)
- Avanzado (emoji)
- Experto (emoji)

**Comment by Villanuevand** [comment]
- Novato 😊
- Intermedio 😃
- Avanzado 😎
- Jedi 🤑

**Comment by edwinvrgs** [comment]
- Saltamontes 🙇 
- Ninja 🕶
- Jedi 💂 
- Maestro jedi 👽

**Comment by edwinvrgs** [comment]
- Saltamontes ☁️ 
- Aprendiz 🌞 
- Ninja ⚡️ 
- Jedi 🔥

**Comment by jqEmprendedorVE** [comment]
Si lo hacemos sencillo 
Novato :blush:
Intermedio :smiley:
Avanzado :sunglasses:
Jedi :money_mouth_face:

**Comment by edwinvrgs** [comment]
Propongo que el emoji del último nivel sea una llama (🔥) , para que vaya acorde con el tema de firebase 😄

**Comment by Villanuevand** [comment]
- Novato 😊
- Intermedio 😃
- Avanzado 😎
- David East 🔥

**Comment by jqEmprendedorVE** [comment]
Creo que casí ya esta...

Salvo que Dave East, no me suena

**Comment by edwinvrgs** [comment]
Misma opinión de @jqEmprendedorVE, puede ser Jedi 🔥 🤔

**Comment by Villanuevand** [comment]
uffff... @jqEmprendedorVE lo que te pierdes... solo te digo google "firebase David East" 😊
Voy a adelantar... Dave East es el lead de AngularFire2  y otras cositas en Firebase 😊

https://github.com/davideast

CodingDoug? 
Andrew Lee? 

¿Nada?

**Comment by jqEmprendedorVE** [comment]
Lo dices por David East

**Comment by jqEmprendedorVE** [comment]
Ah ok... ya vi... el es de la serie de cursos

**Comment by Villanuevand** [comment]
My foul

**Comment by jqEmprendedorVE** [comment]
Pero quedaría entonces 

Novato :blush:
Intermedio :smiley:
Avanzado :sunglasses:
David East :fire:

**Comment by JoseCed** [comment]
Ya casi muchachos :

Novato :blush:
Intermedio :smiley:
Avanzado :sunglasses:
FireExperto :fire:

Los emojis para mi ya estan definidos...

**Comment by edwinvrgs** [comment]
Firejedi? 🤔

**Comment by jqEmprendedorVE** [comment]
Jejeje en es caso dejamos 

- FirePana :fire:

**Comment by jqEmprendedorVE** [comment]
Esta bien pues :smile:

**Comment by jqEmprendedorVE** [comment]
Que tal 

- FireMaster  :fire:

**Comment by edwinvrgs** [comment]
Bueno, creo que la conversación se redujo a decidir el nombre del nivel mas pro. Otra opción:

Firesensei 🔥

**Comment by Villanuevand** [comment]
David East? 🔥

**Comment by mchirino89** [comment]
Dado que queremos dejar un sello criollo y estamos haciendo lo posible por mantener el repo libre de anglicismos, opino que no deberíamos darle el nombre propio (por muy erudito que sea en la materia) de David East al último nivel. Por esto me inclino más por opciones como _FireExperto_ o incluso _Maestro jedi_ aunque este último contradice un poco mi idea principal.

**Comment by edwinvrgs** [comment]
Firegocho? 🔥 😆

**Comment by JoseCed** [comment]
Compañeros viendo que ya tenemos los emojis listos y tres niveles  vamos a decir el 4 Nivel acá tenemos las propuestas:

* David East
* FireExperto
* FireMaster
* FireSensei
* FireJedi
* MaestroJedi

Creo que la iniciativa va tendiendo hacia Fire....

**Comment by jobsamuel** [comment]
David what... ? :thinking:

**Comment by JoseCed** [comment]
@jobsamuel es la propuesta de nuestro compañero @Villanuevand explico sus razones por #telegram

**Comment by jobsamuel** [comment]
Eso me pasa por leer primero esto @JoseCed :sweat_smile:

**Comment by jqEmprendedorVE** [comment]
Jaja si  todo apunta a

- **Fire**[complete aquí] :fire:

**Comment by jobsamuel** [comment]
Propongo que el último nivel sea: **FireVader** :fire::fire::fire:

> _edit:_ Por la simple razón que expresa poder (por Darth Vader), es geek, poco común y suena cool.

**Comment by JMEspiz** [comment]
No se si ya cerro la votacion.. pero siguindo el logo yo votaria por:

- Fosforo 🔥
- Antorcha 🔥🔥
- Fogata 🔥🔥🔥
- Piromano 🔥🔥🔥🔥

**Comment by Villanuevand** [comment]
Me gusta esa propuesta de @JMEspiz

**Comment by leocabeza** [comment]
Genial la propuesta de @JMEspiz

**Comment by anhurtadop** [comment]
Seria genial, usar los niveles de los Jedi jajajajajajajajajaja

- Padawan 🔥
- Caballero 🔥🔥🔥
- Guardián 🔥🔥🔥🔥 
- Maestro 🔥🔥🔥🔥🔥

**Comment by jqEmprendedorVE** [comment]
Con los iconos de fuego combinan mas jeje los niveles de llamitas y da estilo tipo rating

**Comment by anhurtadop** [comment]
@jqEmprendedorVE así es jajajajaja da signo de poder.

**Comment by jqEmprendedorVE** [comment]
Pero por votación creo que queda 

Fosforo
Antorcha
Fogata 
Piromano

**Comment by jqEmprendedorVE** [comment]
Hecho nos quedamos con

Fosforo :fire:
Antorcha :fire::fire:
Fogata :fire::fire::fire:
Piromano :fire::fire::fire::fire:
