### ISSUE TITLE
Organizar lista de aplicaciones compartidas

### ISSUE THREAD

**Issue by jqEmprendedorVE** [firebaseve/firebase-increible#9]
Hola #FirePanas

Siguiendo la linea de ideas compartida y con la determinación de seguir definiendo la comunidad abro este Issue para recolectar ideas de armar nuestro Firebase-increible

Inicialmente, podemos clasificar la **Lista de Aplicaciones** por áreas

- Web
- Android
- Ios

O puede ser por Frameworks:

- Angular
- React
- Vuejs
- Mobile
- Ios
- Otros

Un ejemplo de publicación

## Vuejs

[Todo-list en Vuejs 2.0+Vuex+Firebase](https://todolist-lab.firebaseapp.com/) hecho por [Julio Quintana](https://github.com/jqEmprendedorVE/todolist-vuejs)

Notend que el primer enlace menciona la descripción del proyecto y apunta a la url demo seguido de 'hecho por ' mas el nombre del desarrollador que es enlace al repo en github....

Hasta aquí esto, que les parece?

**Comment by JoseCed** [comment]
Que tal #Firepanas   yo ofrezco la siguiente estructura:

* Web
* Android
* Ios

el mas complicado puede ser **Web** y alli propongo colocar  los repo de la siguiente manera

## NombreProyecto/NombreFramework/ServiciosFirebase

El agregado del #firepana @jqEmprendedorVE sombre el nombre del desarrollador me gusta para ofrecer los créditos a quien se esforzó y nos colaboró.

**Comment by Villanuevand** [comment]
Que les parece esta: 

### Vue
- [Todo-list en Vuejs 2.0+Vuex+Firebase](https://todolist-lab.firebaseapp.com/) por: @jqEmprendedorVE | 😊 (emojiDificultad)

Es decir: 

1. Nombre con enlace del proyecto.
2. Mention al usuario en github del autor.
3. Emoji de dificultad (pendiente por definir).

### ¿Que ganamos con esto? 

1. Con el nombre y enlace hacia el proyecto, visibilidad y posibles estrellas 🌟.
2. Con el mention del usuario, un enlace al perfil.. y que la gente conozca sus otros proyectos...
3. Emoji, establecer visualmente la dificultad de una manera cool y amena. 

¿Qué opinan?

**Comment by undelete** [comment]
Me gusta la idea de Andrés . Lo qué hace falta es el nivel de emojis para la dificultad!

**Comment by jqEmprendedorVE** [comment]
+1 con los emojis

Y bien incluir #FirePana @colaborador

La categoría Web la podemos subclasificar

**Comment by Villanuevand** [comment]
No solo los emojis @undelete , también hace falta definir los niveles de dificultad.

**Comment by Villanuevand** [comment]
Es importante destacar que en `README.md` del repo tenemos que hacer  un listado tal cual lo comenta @jqEmprendedorVE.  Ahí estarán los frameworks y aplicaciones listadas. 

Y cada uno tendrá un file puntual separado.

**Comment by mchirino89** [comment]
Buenas tardes, estoy de acuerdo con @jqEmprendedorVE: la categoría _Web_ es muy amplia así que se debería subclasificar. 

Un pequeño pero a la vez GRAN detalle que debo acotar: es *iOS* (_i_ minúscula, resto mayúscula),

**Comment by Villanuevand** [comment]
Si, estoy de acuerdo... 

Sería algo así: 

- Web
  - Angular
  - React
  - Vue
  - Ember
  - JQuery xD 
  - Node
- Android
- iOS

**Comment by jqEmprendedorVE** [comment]
Chevere

Para la definición de la complejidad podriamos medirla así:

- Cinta blanca [básico] :eyes: 
- Ninja [Intermedio] :running_man: 
- Jedi [Avanzado] :bowing_man: 
- Iluminado [Firebase Increible] :sunny:

**Comment by Villanuevand** [comment]
La discusión de los niveles debería hacerse en otro repo para no confundir peras con manzanas...  @jqEmprendedorVE

**Comment by jqEmprendedorVE** [comment]
Perfecto

**Comment by jqEmprendedorVE** [comment]
## En resumen vamos así 

- Web
  - Angular
  - React
  - Vue
  - Ember
  - JQuery xD
  - Node
- Android
- iOS

Cada item tendra su .md. Un ejemplo de publicación sería:

> # Vue (Firebase Increible)
> 
> [Todo-list en Vuejs 2.0+Vuex+Firebase](https://todolist-lab.firebaseapp.com/) por: [@jqEmprendedorVE](https://github.com/jqEmprendedorVE/todolist-vuejs) | :blush: (emojiDificultad)

Creo que dejamos el item list en el readme.md con enlaces a los nuevos archivos md de categoría.

**Comment by jqEmprendedorVE** [comment]
Cerrada la rueda... solo queda incluir en el nuevo branch lo del nivel de nivel que ya esta por cerrarse
